baseURL = "https://inclusivenaming.org"
title = "Inclusive Naming Initiative"
disableKinds = ["taxonomy", "taxonomyTerm"]
 copyright = "The Inclusive Naming Initiative authors and collaborating organizations"

enableGitInfo = true

[markup.highlight]
style = "paraiso-dark"

[params]
font_awesome_version = "5.12.0"
description = "Helping projects and companies make consistent, responsible choices to remove harmful language"
favicon = "favicon.png"
repositoryUrl = "https://github.com/inclusivenaming"
contentDir = "/content/"
[params.logos]
navbar = "inclusive-naming-logo.svg"

[[params.social]]
name = "Twitter"
url = "https://twitter.com/inclusivenaming"
icon = "fab fa-twitter"

[[params.social]]
name = "GitHub"
url = "https://github.com/inclusivenaming"
icon = "fab fa-github"

[[params.social]]
name = "Mailing list"
url = "https://groups.google.com/g/inclusivenaming"
icon = "fas fa-envelope"

[[params.fonts]]
name = "Cairo"
sizes = [300, 400, 600, 700, 900]
type = "sans_serif"

[[params.fonts]]
name = "Lexend Deca"
sizes = [400]
type = "heading_font"

[[menu.main]]
name = "About"
url = "#"
weight = 1
identifier ="about"

[[menu.main]]
name = "About the initiative"
url = "/about"
parent = "about"
weight = 1

[[menu.main]]
name = "Project leadership"
url = "/leadership"
parent = "about"
weight = 2

[[menu.main]]
name = "Get involved"
url = "/get-involved"
weight = 3

[[menu.main]]
name = "Resources"
url = "#"
identifier = "lang"
weight = 3

[[menu.main]]
name = "Word replacement list"
url = "/language/word-list"
parent = "lang"
weight = 1

[[menu.main]]
name ="Language evaluation framework"
url = "/language/evaluation-framework"
parent = "lang"
weight = 2

[[menu.main]]
name = "Implementation path"
url = "/language/implementation-path"
parent = "lang"
weight = 3

[[menu.main]]
name = "Related projects"
url = "/related-projects"
weight = 4

[[menu.main]]
name = "FAQs"
url = "/faqs"
weight = 5
